"""Add column username to the User table

Revision ID: 638acc3bc53f
Revises: f1406cbb71e5
Create Date: 2017-05-23 21:11:54.029823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638acc3bc53f'
down_revision = 'f1406cbb71e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
