"""Add categories and Languages

Revision ID: f1406cbb71e5
Revises: 2bf1daf7d962
Create Date: 2017-05-18 15:28:57.612034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1406cbb71e5'
down_revision = '2bf1daf7d962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('last_update', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('last_update', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('release_year', sa.Text(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('rental_duration', sa.Integer(), nullable=False),
    sa.Column('rental_rate', sa.Numeric(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('replacement_cost', sa.Numeric(), nullable=False),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.Column('last_update', sa.TIMESTAMP(), nullable=False),
    sa.Column('special_features', sa.Text(), nullable=True),
    sa.Column('fulltext', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('films')
    op.drop_table('roles')
    op.drop_table('languages')
    op.drop_table('categories')
    # ### end Alembic commands ###
